import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";
import fs from "fs";

register(StyleDictionary);

// Manually extract only the tokens we need.
// Rest of the json is not needed, but it is generated by Token Studio, when you use single-file export.
// They want money for multi-file export.

const collectionName = "DEV.BG";
const tokensFilePath = "./tokens.json";
const tokensJson = JSON.parse(fs.readFileSync(tokensFilePath, "utf8"));
const processedTokens = {
  ...tokensJson[collectionName],
};

const sd = new StyleDictionary({
  excludeParentKeys: true,
  // source: ["tokens.json"],
  tokens: processedTokens,
  preprocessors: ["tokens-studio"],
  platforms: {
    js: {
      transformGroup: "tokens-studio",
      transforms: ["name/camel"], // Apply the custom transform
      buildPath: "build/js/",
      files: [
        { destination: "tokens.js", format: "javascript/es6" },
        { destination: "tokens.cjs", format: "javascript/module" },
        { destination: "tokens.ts", format: "typescript/es6-declarations" },
        { destination: "tokens.json", format: "json" },
      ],
    },
    css: {
      transformGroup: "tokens-studio",
      transforms: ["name/kebab"], // Apply the custom transform
      buildPath: "build/css/",
      files: [{ destination: "variables.css", format: "css/variables" }],
    },
    scss: {
      transformGroup: "tokens-studio",
      transforms: ["name/kebab"], // Apply the custom transform
      buildPath: "build/scss/",
      files: [
        {
          destination: "variables.scss",
          format: "scss/variables",
        },
      ],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
